# Generated by Django 4.1.3 on 2022-12-07 05:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0005_remove_classroom_class_total_amount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teacher', '0003_classtools_teachertype'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClassTools',
            new_name='ClassTool',
        ),
        migrations.RenameModel(
            old_name='TeacherProfiles',
            new_name='TeacherProfile',
        ),
    ]
