# Generated by Django 4.1.3 on 2022-12-08 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
        ('teacher', '0004_rename_classtools_classtool_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='classes_tools',
            field=models.ManyToManyField(to='teacher.classtool'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='serve_or_attend_school',
            field=models.ManyToManyField(to='school.school'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='subjects',
            field=models.ManyToManyField(to='teacher.subject'),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='teacher_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='teacher.teachertype'),
        ),
    ]
