# Generated by Django 4.1.3 on 2022-12-21 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0005_teacherprofile_about_teacherprofile_classes_tools_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='avatars'),
        ),
    ]
