# Generated by Django 4.1.3 on 2022-12-22 06:51

from django.db import migrations, models
import teacher.models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0007_alter_teacherprofile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherprofile',
            name='avatar',
            field=models.ImageField(blank=True, upload_to=teacher.models.upload_to, verbose_name='Avatar'),
        ),
    ]
