# Generated by Django 4.1.3 on 2022-12-17 08:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teacher', '0005_teacherprofile_about_teacherprofile_classes_tools_and_more'),
        ('student', '0003_alter_studentprofile_school'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classroom_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('title', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=500)),
                ('class_date', models.DateTimeField()),
                ('is_free_class', models.BooleanField(default=False)),
                ('class_started_at', models.DateTimeField(auto_now=True)),
                ('class_ended_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator', to='student.studentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ClassroomStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.classroom')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.studentprofile')),
            ],
            options={
                'unique_together': {('classroom', 'student')},
            },
        ),
        migrations.AddField(
            model_name='classroom',
            name='student_count',
            field=models.ManyToManyField(through='classroom.ClassroomStudent', to='student.studentprofile'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teacher.subject'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teacher.teacherprofile'),
        ),
    ]
