# Generated by Django 4.1.3 on 2022-12-17 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='class_ended_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='class_started_at',
            field=models.DateTimeField(null=True),
        ),
    ]
