# Generated by Django 4.1.3 on 2022-12-05 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_classroom_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='creator',
        ),
    ]
