# Generated by Django 4.1.3 on 2022-12-05 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0004_alter_classroom_classroom_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='class_total_amount',
        ),
    ]
