# Generated by Django 4.1.3 on 2022-12-18 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0004_rename_student_count_classroom_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='Pending', max_length=20),
        ),
    ]
