# Generated by Django 4.1.3 on 2022-12-07 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_alter_studentprofile_school'),
        ('classroom', '0005_remove_classroom_class_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator', to='student.studentprofile'),
        ),
    ]
