# Generated by Django 4.1.3 on 2022-12-24 12:25

import classroom.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0008_alter_teacherprofile_avatar'),
        ('student', '0007_alter_studentprofile_avatar'),
        ('classroom', '0008_classroom_school'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRoomTeacherAttachments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to=classroom.models.upload_to, verbose_name='Attachment')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.classroom')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.teacherprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ClassRoomStudentAttachments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to=classroom.models.upload_to, verbose_name='Attachment')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.classroom')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.studentprofile')),
            ],
        ),
    ]
