# Generated by Django 4.1.3 on 2022-12-25 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0009_classroomteacherattachments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroomstudentattachments',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='classroomteacherattachments',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
