# Generated by Django 4.1.3 on 2022-12-05 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='school',
            field=models.CharField(choices=[(1, 'Northview High School'), (2, 'Lambert High School')], max_length=200),
        ),
    ]
