# Generated by Django 4.1.3 on 2022-12-07 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
        ('student', '0002_alter_studentprofile_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='school.school'),
        ),
    ]
